project:
  type: website

website:
  title: "Prince Heer - MBA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd
      - skills.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
